### ISSUE TITLE
Install NodeGit threw an error 

### ISSUE THREAD

**Issue by cyan92128505** [CodingWorkshop/Bumblebee#2]
When the electron is start ,and threw an error.
```
$ electron ./electron

App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\D:\Bumblebee\node_modules\nodegit\build\Release\nodegit.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Bumblebee\node_modules\nodegit\dist\nodegit.js:11:12)
```

**Comment by cyan92128505** [comment]
The of electron in Bumblebee  that it is '1.6.4'
First, we should change the version of electron to 1.6.4, also update electron's version in global.
Second, remove node-module in Bumblebee.
Third, exec command in Bumblebee
```
export BUILD_ONLY=1
export npm_config_target=1.6.4
export npm_config_disturl=https://atom.io/download/atom-shell
export npm_config_runtime=electron
export npm_config_build_from_source=true
npm install
```
